description = "Summarize some files"
template_path = "summarize.liquid"

[model]
model = "gpt-3.5-turbo-1106"
# model = "mistrallite"
temperature = 0.7
max_tokens = 2000
# Also supports top_p, frequency_penalty, presence_penalty, stop, and max_tokens

[options]
len = { type = "int", description = "The length of the summary", optional = true }
title = { type = "string", optional = true, description = "The title of the transcript" }
style = { type = "string", default = "concise" }

