product_name = "SBBP"
company_name = "Daniel Imfeld"

default_auth_scope = "model"

api_dir = "api"
web_dir = "web"


shared_types = [
  "crate::models::video::VideoProcessingState",
]

[server]
dotenv = true
hosts = ["localhost"]

[formatter]
js = ["biome", "format", "--stdin-file-path=stdin.ts" ]
rust = ["rustfmt", "+nightly"]
sql = ["pg_format"]

[database]
migrate_on_start = true

[email]
provider = "none"
from = "daniel@imfeld.dev"

[storage.bucket.uploads]
bucket = "sbbp-uploads"
provider = "disk"

[storage.bucket.images]
bucket = "sbbp-images"
provider = "disk"

[storage.provider.disk]
type = "local"
base_path = "storage"


[job.download]
worker = "download"

[job.extract]
worker = "ffmpeg"

[job.analyze]
worker = "analyze"

[job.summarize]
worker = "summarize"

[worker.download]
max_concurrency = 2

[worker.ffmpeg]
max_concurrency = 4

[worker.analyze]
max_concurrency = 4

[worker.summarize]
max_concurrency = 2

